### ISSUE TITLE
fecking doot doot

### ISSUE THREAD

**Issue by mdsumner** [mdsumner/gdal-builds#6]
geopandas.read_file("/vsicurl/https://github.com/mdsumner/equi7grid/raw/main/data-raw/equi7grid.gpkg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 271, in _read_file
    engine = _check_engine(engine, "'read_file' function")
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 120, in _check_engine
    raise ImportError(
ImportError: The 'read_file' function requires the 'pyogrio' or 'fiona' package, but neither is installed or imports correctly.
Importing fiona resulted in: /usr/local/lib/libgdal.so.34: undefined symbol: _ZNK5arrow16KeyValueMetadata8ContainsESt17basic_string_viewIcSt11char_traitsIcEE
Importing pyogrio resulted in: /usr/local/lib/libgdal.so.34: undefined symbol: _ZNK5arrow16KeyValueMetadata8ContainsESt17basic_string_viewIcSt11char_traitsIcEE

**Comment by mdsumner** [comment]
actually it works, just import pyogrio first
